# Generated by Django 2.0.1 on 2019-09-20 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190920_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now(), editable=False, verbose_name='publish_date'),
        ),
    ]
