# Generated by Django 2.0.1 on 2019-09-25 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190920_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=100, verbose_name='选项'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='vote',
            field=models.IntegerField(default=0, verbose_name='得票数'),
        ),
        migrations.AlterField(
            model_name='question',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now(), editable=False, verbose_name='publish_date'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='问题'),
        ),
    ]
